# ローカルはCtrl+b、SSH先はCtrl+a
if-shell '[ -z "$SSH_CONNECTION" ]' 'set -g prefix C-b ; bind C-b send-prefix' 'set -g prefix C-a ; bind C-a send-prefix'

set -g mouse on

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g message-style bg=green,fg=black
bind r source-file ~/.tmux.conf \; display "Reloaded!"

set -g status-position top
set -g status-style bg=colour235,fg=colour136
set -g status-left "#[fg=green]● #[fg=green]#H "
set -g status-right "#[fg=cyan]%Y/%m/%d %H:%M"

# SSH先は黄色（Macウィンドウボタンの黄色）＋時計非表示＋背景透明
if-shell '[ -n "$SSH_CONNECTION" ]' 'set -g status-style bg=default ; set -g status-left "#[fg=colour226]● #[fg=colour226]#H " ; set -g status-right ""'

# rootは全体を赤に＋丸も赤（最優先）
if-shell '[ "$(id -u)" = "0" ]' 'set -g status-style bg=colour160,fg=white ; set -g status-left "#[fg=colour196]● #[fg=white]#H "'

set -g base-index 1
setw -g pane-base-index 1

# ウィンドウリストは番号だけ
setw -g window-status-format " #I "
setw -g window-status-current-format " #I "

setw -g mode-keys vi
#EOF
